name: Run linter

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ruff linter
        run: |
          pip install ruff
      
      - name: Run the linter
        run: |
          ruff check
